version: '3.8'

services:
  nestjs_api:
    container_name: nestjs_gateway
    hostname: nestjs_gateway
    image: nestjs_gateway:1.0.0
    environment:
      - NODE_ENV:${NODE_ENV}
    build:
      context: .
      args:
        - NODE_ENV="${NODE_ENV}"
      dockerfile: ./Dockerfile
      target: build
    command: npm run start:debug
    env_file:
      - .env
    ports:
      - "3000:3000"
    #volumes:
    #  - .:/app
    #  - ./app/node_modules
    networks:
      - nestjs-network
    restart: unless-stopped


networks:
  nestjs-network:
    name: nestjs-network
    external: true
